name: CI Check

on:
  pull_request:
    branches:
      - release
    paths:
      - "CI_test/**" # you can customize this to specific paths

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: npm install, build, and test
        run: |
          cd CI_test
          npm install
          npm run build --if-present
          npm run test --if-present
